### ISSUE TITLE
Chaging when device off

### ISSUE THREAD

**Issue by gandyprakoso** [JeyKul/8890-8895#1]
when the device turns off then I charge it, the charging animation doesn't appear.  the only way to turn it on is to press the bixby + volume and power buttons.. is there a way to fix this? Galaxy note 8 - N950F

**Comment by JeyKul** [comment]
Hi, I've been talking to some people about that problem. 
It seems to be known actually. Tho it shoudn't compromize your charging. It should keep charging like you are used to it.

I hope I could clear some things up for you. Greetings!
